// Package cache provides semantic caching for the Prism AI gateway.
//
// It caches responses to semantically similar requests using vector embeddings
// generated by a local Ollama model (nomic-embed-text). A VP-tree index provides
// O(log n) nearest-neighbor lookups by cosine similarity.
//
// Per-ServiceType policies control which services are cached: deterministic
// services (chat, embedding) are cached by default; stochastic services
// (image generation, 3D) are not.
//
// Cached responses are stored sanitized with PII mappings encrypted per-entry
// using AES-256-GCM. PII never appears in plaintext on disk.
package cache
